name: Oli test tag trigger 3

on:
  push:
    tags:
      - 'olitest_*'
    branches:
        - main
      

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag ${{github.ref_name}}   due to ${{ github.event_name }} Ref ${{gigithub.event.ref}}
        run: |
          echo Tag ${{github.ref_name}} Event ${{ github.event_name }} 
          echo Ref [${{github.event.ref}}] Base [${{github.event.base_ref}}]
          echo type ${{github.ref_type}}