name: Oli test tag trigger 3

on:
  push:
      tags:
        - 'olitest_*'

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag ${{github.ref_name}}        
        run: |
          echo Alternative ${{github.ref_name}}