name: Oli test tag trigger

on:
  create:
    ref_type: tag
    ref: olitest_*

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-step
        shell: bash
        run: echo "Running step triggered by tag2"

