name: Oli test tag trigger 2

on:
  push:
      tags:
        - olitest_*

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo-step
        shell: bash
        run: echo "Running step triggered by some push"

